define user express greeting
  "hello"
  "hi"

define bot express greeting
  "Hello there!! Can I help you today?"

define flow hello
  user express greeting
  bot express greeting

define flow
  user express insult
  bot express calmly willingness to help

define flow
    user ...
    $answer = execute qa_ccl_chain(query=$last_user_message)
    bot $answer
